---

- name: Override the default become method
  set_fact:
    ansible_become_method: '{{ basics_initial_become_method }}'
    ansible_become_flags: '{{ basics_initial_become_flags }}'

- name: Bootstrap pkg(8) using raw mode
  raw: /usr/sbin/pkg bootstrap -y
  changed_when: false

- name: Install the initial packages using raw mode
  raw: pkg install -y {{ basics_initial_pkgs|join(' ') }}
  changed_when: false

- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Update /etc/rc.conf with the new hostname
  sysrc:
    name: hostname
    value: '{{ inventory_hostname }}'

- name: Configure sudo(8) to allow members of group wheel
  copy:
    src: sudo-wheel
    dest: '{{ basics_sudoers_d_wheel }}'
    mode: 0440
    owner: root
    group: wheel
    validate: '{{ basics_visudo }} -cf %s'

- name: Configure pam_ssh_agent_auth(8) for sudo authentication
  template:
    src: sudo.pam.j2
    dest: '{{ basics_pamd_sudo }}'
    mode: 0644
    owner: root
    group: wheel

- name: Create groups for local users
  group:
    name: '{{ item.group }}'
  loop: '{{ basics_users }}'

- name: Create local users
  user:
    name: '{{ item.user }}'
    comment: '{{ item.comment|default(omit) }}'
    shell: '{{ item.shell|default(omit) }}'
    group: '{{ item.group|default(item.user) }}'
    groups: '{{ item.other_groups|default([]) }}'
    password: '{{ item.password|default("*") }}'
    update_password: '{{ item.update_password|default(false)|ternary("always", "on_create") }}'
    create_home: yes
    move_home: yes
  loop: '{{ basics_users }}'

- name: Manage authorized_keys for users
  authorized_key:
    user: '{{ item.0.user }}'
    key: '{{ item.1 }}'
  with_subelements:
    - '{{ basics_users }}'
    - ssh_pub_keys

- name: Add users keys to {{ basics_sudo_authorized_keys }}
  lineinfile:
    path: '{{ basics_sudo_authorized_keys }}'
    create: yes
    owner: root
    group: wheel
    mode: 0644
    state: present
    line: '{{ item.1 }}'
  with_subelements:
    - '{{ basics_users }}'
    - ssh_pub_keys
  when: item.0.auth_sudo | default(false)

...
