---

- name: Install nginx
  pkgng:
    name: nginx
    state: latest

- name: Set up nginx configuration
  template:
    src: nginx.conf.j2
    dest: '{{ nginx_config }}'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - enable-reload-nginx

...
