---

# Additional shells to install
#basics_user_shells:
#  - bash
#  - zsh

# User accounts to create

basics_users:
  - user: matthew
    comment: Matthew Seaman
    shell: /bin/tcsh
    group: matthew
    other_groups:
      - wheel
      - operator
    password: '*'
    ssh_pub_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILGZltCKvFNlSyE7O1HMGY0KZGMxImdRC8KLxqL0Jmhw matthew@lucid-nonsense.infracaninophile.co.uk'
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAR6DC2oyHLBqkZ9+lUu1K0h16pDSG54fr1jVBJZ7/Ja matthew@freebsd.org'
    update_password: true
    auth_sudo: true

pkg_enabled_repos:
  - name: mypackages
    url: "https://{{ hostvars[groups['poudriere'][0]]['ansible_fqdn']/${ABI}"
    signature_type: pubkey
    pubkey: /usr/local/etc/pkg/mypackages.pem
    enabled: 'yes'
    priority: 1

pkg_repo_pubkeys:
  - name: mypackages
    pubkey: "{{ hostvars[groups['poudriere'][0]]['poudriere_pubkey'] }}"

...
