---

pkg_enabled_repos:
  - name: mypackages
    url: 'file:///usr/local/poudriere/data/packages/12_1a-default'
    signature_type: pubkey
    pubkey: /usr/local/etc/pkg/mypackages.pem
    enabled: 'yes'
    priority: 1

...
