---
# Immediate post-install setup to make a FreeBSD machine behave like a
# good citizen of the ansible ecosphere.  Install python and sudo, add
# local users with SSH key based access

 - hosts: freebsd-12-zfs
   gather_facts: no
   become: yes
   roles:
     - basics
#     - role: pam_sudo
#       vars: 
#         users: '{{ basics_users }}'

...