---
# Immediate post-install setup to make a FreeBSD machine behave like a
# good citizen of the ansible ecosphere.  Install python and sudo, add
# local users with SSH key based access

 - hosts: poudriere
   gather_facts: no
   become: yes
   roles:
     - basics

...
